-- Liquibase ChangeSet pour créer le schéma complet de la base de données WaraLoyer
-- Ce script regroupe tous les patchs précédents en une seule migration.

-- ChangeSet id: consolidated-full-schema
-- Author: votre_nom_d_utilisateur
-- Date: 2025-08-25

-- Création de la table 'app_user' pour l'authentification
CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          first_name VARCHAR(255) NOT NULL,
                          last_name VARCHAR(255) NOT NULL,
                          created_at TIMESTAMP DEFAULT NOW(),
                          subscription_end_date TIMESTAMP DEFAULT NOW() + INTERVAL '1 year' NOT NULL
);

-- Création de la table 'role'
CREATE TABLE role (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(50) NOT NULL UNIQUE
);

-- Insertion des rôles par défaut
INSERT INTO role (name) VALUES ('ROLE_USER');
INSERT INTO role (name) VALUES ('ROLE_ADMIN');

-- Création de la table de jointure 'user_roles'
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id)
);

-- Création de la table 'client_config' pour les paramètres utilisateur
CREATE TABLE client_config (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               owner_email VARCHAR(255) NOT NULL,
                               sms_reminder_message TEXT NOT NULL,
                               sms_relance_message TEXT NOT NULL,
                               reminder_days_before INTEGER NOT NULL,
                               relance_days_after INTEGER NOT NULL,
                               default_payment_method VARCHAR(50) NOT NULL,
                               rib_details TEXT,
                               mobile_money_link VARCHAR(255),
                               contact_person_details TEXT,
                               user_id BIGINT NOT NULL
);

-- Création de la table 'property' pour les biens immobiliers (ID corrigé)
CREATE TABLE property (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          address VARCHAR(255) NOT NULL,
                          type VARCHAR(50) NOT NULL,
                          rent_amount DECIMAL(19, 2) NOT NULL,
                          charges_amount DECIMAL(19, 2) NOT NULL,
                          description TEXT,
                          rent_payment_date INTEGER NOT NULL,
                          user_id BIGINT NOT NULL
);

-- Création de la table 'tenant' pour les locataires (ID et clés étrangères corrigées)
CREATE TABLE tenant (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        first_name VARCHAR(255) NOT NULL,
                        last_name VARCHAR(255) NOT NULL,
                        email VARCHAR(255) NOT NULL,
                        phone_number VARCHAR(50) NOT NULL,
                        rent_start_date DATE NOT NULL,
                        user_id BIGINT NOT NULL,
                        property_id BIGINT
);

-- Création de la table 'rental' pour les loyers et les relances (ID et clés étrangères corrigées)
CREATE TABLE rental (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        due_date DATE NOT NULL,
                        amount_due DECIMAL(19, 2) NOT NULL,
                        payment_date DATE,
                        status VARCHAR(50) NOT NULL,
                        is_reminder_sent BOOLEAN DEFAULT FALSE NOT NULL,
                        last_reminder_sent_date DATE,
                        is_relance_sent BOOLEAN DEFAULT FALSE NOT NULL,
                        last_relance_sent_date DATE,
                        comments TEXT,
                        monthly_costs DECIMAL(19, 2),
                        taxes DECIMAL(19, 2),
                        user_id BIGINT NOT NULL,
                        property_id BIGINT NOT NULL,
                        locataire_id BIGINT NOT NULL
);

-- Création de la table 'sms_log' pour l'historique des communications
CREATE TABLE sms_log (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         type VARCHAR(50) NOT NULL,
                         message TEXT NOT NULL,
                         sent_date TIMESTAMP NOT NULL,
                         status VARCHAR(50) NOT NULL,
                         user_id BIGINT NOT NULL,
                         rental_id BIGINT,
                         locataire_id BIGINT,
                         property_id BIGINT
);

-- Ajout des clés étrangères (après la création de toutes les tables)

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES role(id);

ALTER TABLE client_config
    ADD CONSTRAINT fk_client_config_user FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE property
    ADD CONSTRAINT fk_property_user FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE tenant
    ADD CONSTRAINT fk_tenant_user FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE tenant
    ADD CONSTRAINT fk_tenant_property FOREIGN KEY (property_id) REFERENCES property(id);

ALTER TABLE rental
    ADD CONSTRAINT fk_rental_user FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE rental
    ADD CONSTRAINT fk_rental_property FOREIGN KEY (property_id) REFERENCES property(id);

ALTER TABLE rental
    ADD CONSTRAINT fk_rental_locataire FOREIGN KEY (locataire_id) REFERENCES tenant(id);

ALTER TABLE sms_log
    ADD CONSTRAINT fk_sms_log_user FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE sms_log
    ADD CONSTRAINT fk_sms_log_rental FOREIGN KEY (rental_id) REFERENCES rental(id);

ALTER TABLE sms_log
    ADD CONSTRAINT fk_sms_log_locataire FOREIGN KEY (locataire_id) REFERENCES tenant(id);

ALTER TABLE sms_log
    ADD CONSTRAINT fk_sms_log_property FOREIGN KEY (property_id) REFERENCES property(id);
