-- Création de la table 'app_user' pour l'authentification
CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          first_name VARCHAR(255) NOT NULL,
                          last_name VARCHAR(255) NOT NULL,
                          created_at TIMESTAMP DEFAULT NOW(),
                          subscription_end_date DATE NOT NULL

);

-- Création de la table 'client_config' pour les paramètres utilisateur
CREATE TABLE client_config (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL, -- Clé étrangère vers l'utilisateur
                               owner_email VARCHAR(255) NOT NULL,
                               sms_reminder_message TEXT NOT NULL,
                               sms_relance_message TEXT NOT NULL,
                               reminder_days_before INTEGER NOT NULL,
                               relance_days_after INTEGER NOT NULL,
                               default_payment_method VARCHAR(50) NOT NULL,
                               rib_details TEXT,
                               mobile_money_link VARCHAR(255),
                               contact_person_details TEXT
);

-- Création de la table 'property' pour les biens immobiliers
CREATE TABLE property (
                          id VARCHAR(255) PRIMARY KEY,
                          tenant_id BIGINT NOT NULL, -- Clé étrangère vers le client
                          name VARCHAR(255) NOT NULL,
                          address VARCHAR(255) NOT NULL,
                          type VARCHAR(50) NOT NULL,
                          rent_amount DECIMAL(19, 2) NOT NULL,
                          charges_amount DECIMAL(19, 2) NOT NULL,
                          description TEXT,
                          rent_payment_date INTEGER NOT NULL
);

-- Création de la table 'tenant' pour les locataires
CREATE TABLE tenant (
                        id VARCHAR(255) PRIMARY KEY,
                        tenant_id BIGINT NOT NULL, -- Clé étrangère vers le client
                        first_name VARCHAR(255) NOT NULL,
                        last_name VARCHAR(255) NOT NULL,
                        email VARCHAR(255) NOT NULL,
                        phone_number VARCHAR(50) NOT NULL,
                        rent_start_date DATE NOT NULL,
                        property_id VARCHAR(255)
);

-- Création de la table 'rental' pour les loyers et les relances
CREATE TABLE rental (
                        id VARCHAR(255) PRIMARY KEY,
                        tenant_id BIGINT NOT NULL, -- Clé étrangère vers le client
                        property_id VARCHAR(255) NOT NULL,
                        locataire_id VARCHAR(255) NOT NULL, -- Clé étrangère vers le locataire (renommé pour éviter la confusion)
                        due_date DATE NOT NULL,
                        amount_due DECIMAL(19, 2) NOT NULL,
                        payment_date DATE,
                        status VARCHAR(50) NOT NULL,
                        is_reminder_sent BOOLEAN DEFAULT FALSE NOT NULL,
                        last_reminder_sent_date DATE,
                        is_relance_sent BOOLEAN DEFAULT FALSE NOT NULL,
                        last_relance_sent_date DATE,
                        comments TEXT
);

-- Création de la table 'sms_log' pour l'historique des communications
CREATE TABLE sms_log (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         tenant_id BIGINT NOT NULL, -- Clé étrangère vers le client
                         rental_id VARCHAR(255),
                         locataire_id VARCHAR(255), -- Clé étrangère vers le locataire
                         property_id VARCHAR(255),
                         type VARCHAR(50) NOT NULL,
                         message TEXT NOT NULL,
                         sent_date TIMESTAMP NOT NULL,
                         status VARCHAR(50) NOT NULL
);
