-- Liquibase ChangeSet pour créer la table 'tenant_message_log'.
-- Ce script est essentiel pour la fonctionnalité de communication avec les locataires.

-- ChangeSet id: create-tenant-message-log
-- Author: votre_nom_d_utilisateur
-- Date: 2025-08-26

-- Création de la table 'tenant_message_log'
CREATE TABLE tenant_message_log (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    message TEXT NOT NULL,
                                    sent_date TIMESTAMP NOT NULL,
                                    status VARCHAR(50),
                                    user_id BIGINT,
                                    tenant_id BIGINT,
                                    property_id BIGINT
);

-- Ajout des clés étrangères
ALTER TABLE tenant_message_log
    ADD CONSTRAINT fk_tenant_message_log_user
        FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE tenant_message_log
    ADD CONSTRAINT fk_tenant_message_log_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenant(id);

ALTER TABLE tenant_message_log
    ADD CONSTRAINT fk_tenant_message_log_property
        FOREIGN KEY (property_id) REFERENCES property(id);
