-- Liquibase ChangeSet pour créer les tables de rôles et la table de jointure.
-- Cet ensemble de changements est essentiel pour l'implémentation de la sécurité par rôles.

-- ChangeSet id: create-role-tables-and-data
-- Author: votre_nom_d_utilisateur
-- Date: 2025-08-22

-- Création de la table 'role'
CREATE TABLE role (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(50) NOT NULL UNIQUE
);

-- Création de la table de jointure 'user_roles'
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id)
);

-- Ajout des clés étrangères à la table 'user_roles'
ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES role(id);

-- Insertion des rôles par défaut
INSERT INTO role (name) VALUES ('ROLE_USER');
INSERT INTO role (name) VALUES ('ROLE_ADMIN');
