-- db/changelog/04-create-expense-table.sql
-- ChangeSet id: create-expense-table author: votre_nom_d_utilisateur date: 2025-09-12

CREATE TABLE expense (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         rental_id BIGINT NOT NULL,
                         date DATE NOT NULL,
                         amount DECIMAL(19, 2) NOT NULL,
                         description TEXT
);

ALTER TABLE expense
    ADD CONSTRAINT fk_expense_rental FOREIGN KEY (rental_id) REFERENCES rental(id);