-- db/changelog/05-create-tenant-message-log-table.sql
CREATE TABLE tenant_message_log (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    message TEXT NOT NULL,
                                    sent_date TIMESTAMP NOT NULL,
                                    status VARCHAR(50),
                                    user_id BIGINT,
                                    tenant_id BIGINT,
                                    property_id BIGINT
);