-- db/changelog/05-create-tenant-message-log-table.sql
CREATE TABLE tenant_message_log (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    message TEXT NOT NULL,
                                    sent_date TIMESTAMP NOT NULL,
                                    status VARCHAR(50),
                                    rental_id BIGINT REFERENCES rental(id) -- Foreign key to the rental table
);