-- db/changelog/08-create-subscription-table.sql
CREATE TABLE subscription (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(50) NOT NULL UNIQUE,
                              monthly_sms_limit INTEGER NOT NULL
);