# application.yml (fichier principal)
spring:
  profiles:
    active: prod
  mail:
    host: smtp.gmail.com  # Le serveur SMTP de votre fournisseur
    port: 587                      # 587 (TLS) ou 465 (SSL)
    username: waraloyer@gmail.com
    password: uvrlsvovsunqydwi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        # Expose les endpoints health, info, et metrics. '*' expose tout.
        include: 'health, info, metrics, prometheus, mappings, loggers'
  endpoint:
    # Permet de voir les détails complets de l'état de santé
    health:
      show-details: always
    # Configure l'endpoint Prometheus pour le scraping
    prometheus:
      enabled: true