# prometheus.yml (A déployer sur le serveur de monitoring)
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wara-loyer-backend'
    # ATTENTION : Correction du chemin pour correspondre au base-path de Spring Actuator
    metrics_path: '/actuator/prometheus'

    static_configs:
      - targets: ['wara-loyer-back.onrender.com']
        labels:
          application: wara-loyer
    scheme: https